### ISSUE TITLE
Milestone #1 : Init

### ISSUE THREAD

**Issue by kyuchoi95** [Being97/332project#1]
- [x] Worker 실행시 Master IP 주소 입력
` sbt "runMain worker.HelloWorldClient [masterIP]" `
- [x] ConnectionRequestMsg : IP 주소 전달 (Worker -> Master)
- [x] IP 주소 저장 (Master)
- [x] ConnectionDoneMsg
- [ ] Worker IP List Worker들에게 전송

ConnectionRequestMsg 
- workerIP : string

ConnectionDoneMsg
- isConnected : bool

## 실행방법

Master : `sbt "runMain master.Master [workerNum]"`
ex> `sbt "runMain master.Master 2"`

Worker : `sbt "runMain worker.Worker[masterIP]"`
ex> `sbt "runMain worker.Worker 2.2.2.101"`
